### ISSUE TITLE
Support for all the shields from shields.io

### ISSUE THREAD

**Issue by zkochan** [KenanY/shields#9]
I would love to use this package in my module called [mos](https://github.com/zkochan/mos). My module can add badges to README files automatically. I believe I can remove the logic of generating the badges from my module and use this module for that purpose.

What I would need in the shields module is:
- [ ] support for all the shields at shields.io
- [x] the ability to specify the style of the shields

I can work on it and create a pull request if your OK with these new features being part of the shields module.

**Comment by KenanY** [comment]
@zkochan Sound good!
